### ISSUE TITLE
License: Under what license is this project?

### ISSUE THREAD

**Issue by Mafii** [tfennel/desktop-toasts#10]
Other projects from your GitHub org are listed under MIT - what is the license for this project?

**Comment by jeremytbrun** [comment]
I need to know this as well!

**Comment by ChrisGuzak** [comment]
this sample has been incorproated into the main desktop samples: https://github.com/Microsoft/Windows-classic-samples/tree/master/Samples/DesktopToasts.

that should have a clear license

**Comment by Mafii** [comment]
Thank you @ChrisGuzak !
